wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1739414295
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 35
      4: 3.8.20
      5: 0.12.21
      8:
      - 5
algorithm:
  desc: null
  value:
    clip_param: 0.2
    desired_kl: 0.01
    entropy_coef: 0.001
    gamma: 0.994
    lam: 0.9
    learning_rate: 1.0e-05
    lin_vel_idx: 199
    max_grad_norm: 1.0
    num_learning_epochs: 2
    num_mini_batches: 4
    schedule: adaptive
    use_clipped_value_loss: true
    value_loss_coef: 1.0
asset:
  desc: null
  value:
    angular_damping: 0.0
    armature: 0.0
    collapse_fixed_joints: true
    default_dof_drive_mode: 3
    density: 0.001
    disable_gravity: false
    file: '{LEGGED_GYM_ROOT_DIR}/resources/robots/x1/urdf/x1.urdf'
    fix_base_link: false
    flip_visual_attachments: false
    foot_name: ankle_roll
    knee_name: knee_pitch
    linear_damping: 0.0
    max_angular_velocity: 1000.0
    max_linear_velocity: 1000.0
    name: x1
    penalize_contacts_on:
    - base_link
    replace_cylinder_with_capsule: false
    self_collisions: 0
    terminate_after_contacts_on:
    - base_link
    thickness: 0.01
    xml_file: '{LEGGED_GYM_ROOT_DIR}/resources/robots/x1/mjcf/xyber_x1_flat.xml'
commands:
  desc: null
  value:
    curriculum: true
    gait:
    - walk_omnidirectional
    - stand
    - walk_omnidirectional
    gait_time_range:
      rotate:
      - 2
      - 3
      stand:
      - 2
      - 3
      walk_lateral:
      - 2
      - 6
      walk_omnidirectional:
      - 4
      - 6
      walk_sagittal:
      - 2
      - 6
    heading_command: false
    max_curriculum: 1.5
    num_commands: 4
    ranges:
      ang_vel_yaw:
      - -0.6
      - 0.6
      heading:
      - -3.14
      - 3.14
      lin_vel_x:
      - -0.4
      - 1.2
      lin_vel_y:
      - -0.4
      - 0.4
    resampling_time: 25.0
    stand_com_threshold: 0.05
    sw_switch: true
control:
  desc: null
  value:
    action_scale: 0.5
    control_type: P
    damping:
      ankle_pitch_joint: 0.5
      ankle_roll_joint: 0.5
      hip_pitch_joint: 3
      hip_roll_joint: 3.0
      hip_yaw_joint: 4
      knee_pitch_joint: 10
    decimation: 10
    stiffness:
      ankle_pitch_joint: 35
      ankle_roll_joint: 35
      hip_pitch_joint: 30
      hip_roll_joint: 40
      hip_yaw_joint: 35
      knee_pitch_joint: 100
domain_rand:
  desc: null
  value:
    add_dof_lag: true
    add_dof_pos_vel_lag: false
    add_duration:
    - 0
    - 0.1
    - 0.2
    - 0.3
    add_ext_force: false
    add_imu_lag: false
    add_lag: true
    add_update_step: 120000
    added_link_mass_range:
    - 0.9
    - 1.1
    added_mass_range:
    - -3
    - 3
    base_inertial_range:
    - - 0.98
      - 1.02
    - - 0.98
      - 1.02
    - - 0.98
      - 1.02
    com_displacement_range:
    - - -0.05
      - 0.05
    - - -0.05
      - 0.05
    - - -0.05
      - 0.05
    continuous_push: false
    damping_multiplier_range:
    - 0.8
    - 1.2
    dof_lag_timesteps_range:
    - 0
    - 40
    dof_pos_lag_timesteps_range:
    - 7
    - 25
    dof_vel_lag_timesteps_range:
    - 7
    - 25
    ext_force_interval: 1000.0
    ext_force_interval_s: 10
    ext_force_max_xy: 10
    ext_force_max_z: 5
    ext_torque_max: 0
    friction_range:
    - 0.2
    - 1.3
    imu_lag_timesteps_range:
    - 1
    - 10
    joint_10_armature_range:
    - 0.0001
    - 0.05
    joint_10_damping_range:
    - 0.9
    - 1.5
    joint_10_friction_range:
    - 0.5
    - 1.3
    joint_1_armature_range:
    - 0.0001
    - 0.05
    joint_1_damping_range:
    - 0.3
    - 1.5
    joint_1_friction_range:
    - 0.01
    - 1.15
    joint_2_armature_range:
    - 0.0001
    - 0.05
    joint_2_damping_range:
    - 0.3
    - 1.5
    joint_2_friction_range:
    - 0.01
    - 1.15
    joint_3_armature_range:
    - 0.0001
    - 0.05
    joint_3_damping_range:
    - 0.3
    - 1.5
    joint_3_friction_range:
    - 0.01
    - 1.15
    joint_4_armature_range:
    - 0.0001
    - 0.05
    joint_4_damping_range:
    - 0.9
    - 1.5
    joint_4_friction_range:
    - 0.5
    - 1.3
    joint_5_armature_range:
    - 0.0001
    - 0.05
    joint_5_damping_range:
    - 0.9
    - 1.5
    joint_5_friction_range:
    - 0.5
    - 1.3
    joint_6_armature_range:
    - 0.0001
    - 0.05
    joint_6_damping_range:
    - 0.3
    - 1.5
    joint_6_friction_range:
    - 0.01
    - 1.15
    joint_7_armature_range:
    - 0.0001
    - 0.05
    joint_7_damping_range:
    - 0.3
    - 1.5
    joint_7_friction_range:
    - 0.01
    - 1.15
    joint_8_armature_range:
    - 0.0001
    - 0.05
    joint_8_damping_range:
    - 0.3
    - 1.5
    joint_8_friction_range:
    - 0.01
    - 1.15
    joint_9_armature_range:
    - 0.0001
    - 0.05
    joint_9_damping_range:
    - 0.9
    - 1.5
    joint_9_friction_range:
    - 0.5
    - 1.3
    joint_armature_range:
    - 0.0001
    - 0.05
    joint_coulomb_range:
    - 0.1
    - 0.9
    joint_damping_range:
    - 0.3
    - 1.5
    joint_friction_range:
    - 0.01
    - 1.15
    joint_viscous_range:
    - 0.05
    - 0.1
    lag_timesteps_range:
    - 5
    - 40
    link_com_displacement_range:
    - - -0.005
      - 0.005
    - - -0.005
      - 0.005
    - - -0.005
      - 0.005
    link_inertial_range:
    - - 0.98
      - 1.02
    - - 0.98
      - 1.02
    - - 0.98
      - 1.02
    max_push_ang_vel: 0.2
    max_push_force: 0.5
    max_push_torque: 0.5
    max_push_vel_xy: 0.2
    motor_offset_range:
    - -0.035
    - 0.035
    push_duration:
    - 0
    - 0.05
    - 0.1
    - 0.15
    - 0.2
    - 0.25
    push_force_noise: 0.5
    push_interval: 400.0
    push_interval_s: 4
    push_robots: true
    push_torque_noise: 0.5
    randomize_base_inertia: false
    randomize_base_mass: true
    randomize_com: true
    randomize_coulomb_friction: true
    randomize_dof_lag_timesteps: true
    randomize_dof_lag_timesteps_perstep: false
    randomize_dof_pos_lag_timesteps: false
    randomize_dof_pos_lag_timesteps_perstep: false
    randomize_dof_vel_lag_timesteps: false
    randomize_dof_vel_lag_timesteps_perstep: false
    randomize_friction: true
    randomize_gains: true
    randomize_imu_lag_timesteps: true
    randomize_imu_lag_timesteps_perstep: false
    randomize_joint_armature: true
    randomize_joint_armature_each_joint: false
    randomize_joint_damping: true
    randomize_joint_damping_each_joint: false
    randomize_joint_friction: true
    randomize_joint_friction_each_joint: false
    randomize_lag_timesteps: true
    randomize_lag_timesteps_perstep: false
    randomize_link_com: false
    randomize_link_inertia: false
    randomize_link_mass: true
    randomize_motor_offset: true
    randomize_torque: true
    restitution_range:
    - 0.0
    - 0.4
    stiffness_multiplier_range:
    - 0.8
    - 1.2
    torque_multiplier_range:
    - 0.8
    - 1.2
    update_step: 48000
env:
  desc: null
  value:
    add_stand_bool: false
    c_frame_stack: 3
    env_spacing: 3.0
    episode_length_s: 24
    frame_stack: 66
    num_actions: 12
    num_commands: 5
    num_envs: 4096
    num_observations: 3102
    num_privileged_obs: 219
    num_single_obs: 47
    send_timeouts: true
    short_frame_stack: 5
    single_linvel_index: 53
    single_num_privileged_obs: 73
    use_ref_actions: false
init_member_classes:
  desc: null
  value: {}
init_state:
  desc: null
  value:
    ang_vel:
    - 0.0
    - 0.0
    - 0.0
    default_joint_angles:
      left_ankle_pitch_joint: -0.21
      left_ankle_roll_joint: 0.0
      left_hip_pitch_joint: 0.4
      left_hip_roll_joint: 0.05
      left_hip_yaw_joint: -0.31
      left_knee_pitch_joint: 0.49
      right_ankle_pitch_joint: -0.21
      right_ankle_roll_joint: 0.0
      right_hip_pitch_joint: -0.4
      right_hip_roll_joint: -0.05
      right_hip_yaw_joint: 0.31
      right_knee_pitch_joint: 0.49
    lin_vel:
    - 0.0
    - 0.0
    - 0.0
    pos:
    - 0.0
    - 0.0
    - 0.7
    rot:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
noise:
  desc: null
  value:
    add_noise: true
    noise_level: 1.5
    noise_scales:
      ang_vel: 0.2
      dof_pos: 0.02
      dof_vel: 1.5
      gravity: 0.05
      height_measurements: 0.1
      lin_vel: 0.1
      quat: 0.1
normalization:
  desc: null
  value:
    clip_actions: 100.0
    clip_observations: 100.0
    obs_scales:
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 0.05
      height_measurements: 5.0
      lin_vel: 2.0
      quat: 1.0
policy:
  desc: null
  value:
    actor_hidden_dims:
    - 512
    - 256
    - 128
    critic_hidden_dims:
    - 768
    - 256
    - 128
    filter_size:
    - 32
    - 16
    in_channels: 66
    init_noise_std: 1.0
    kernel_size:
    - 6
    - 4
    lh_output_dim: 64
    state_estimator_hidden_dims:
    - 256
    - 128
    - 64
    stride_size:
    - 3
    - 2
rewards:
  desc: null
  value:
    base_height_target: 0.61
    cycle_time: 0.7
    feet_to_ankle_distance: 0.041
    final_swing_joint_delta_pos:
    - 0.25
    - 0.05
    - -0.11
    - 0.35
    - -0.16
    - 0.0
    - -0.25
    - -0.05
    - 0.11
    - 0.35
    - -0.16
    - 0.0
    foot_max_dist: 1.0
    foot_min_dist: 0.2
    max_contact_force: 700
    only_positive_rewards: true
    scales:
      action_smoothness: -0.002
      base_acc: 0.2
      base_height: 0.2
      collision: -1.0
      default_joint_pos: 1.0
      dof_acc: -1.0e-07
      dof_pos_limits: -10.0
      dof_torque_limits: -0.1
      dof_vel: -2.0e-08
      dof_vel_limits: -1
      feet_air_time: 1.2
      feet_clearance: 1.0
      feet_contact_forces: -0.01
      feet_contact_number: 2.0
      feet_distance: 0.2
      feet_rotation: 0.3
      foot_slip: -0.1
      knee_distance: 0.2
      low_speed: 0.2
      orientation: 1.0
      ref_joint_pos: 2.2
      stand_still: 2.5
      torques: -8.0e-09
      track_vel_hard: 0.5
      tracking_ang_vel: 1.1
      tracking_lin_vel: 1.8
      vel_mismatch_exp: 0.5
    soft_dof_pos_limit: 0.98
    soft_dof_vel_limit: 0.9
    soft_torque_limit: 0.9
    target_feet_height: 0.03
    target_feet_height_max: 0.06
    tracking_sigma: 5
runner:
  desc: null
  value:
    algorithm_class_name: DHPPO
    checkpoint: -1
    experiment_name: x1_dh_stand
    load_run: -1
    max_iterations: 20000
    num_steps_per_env: 24
    policy_class_name: ActorCriticDH
    resume: false
    resume_path: null
    run_name: v1
    save_interval: 100
runner_class_name:
  desc: null
  value: DHOnPolicyRunner
safety:
  desc: null
  value:
    pos_limit: 1.0
    torque_limit: 0.85
    vel_limit: 1.0
seed:
  desc: null
  value: 5
sim:
  desc: null
  value:
    dt: 0.001
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      bounce_threshold_velocity: 0.5
      contact_collection: 2
      contact_offset: 0.01
      default_buffer_size_multiplier: 5
      max_depenetration_velocity: 1.0
      max_gpu_contact_pairs: 8388608
      num_position_iterations: 4
      num_threads: 10
      num_velocity_iterations: 0
      rest_offset: 0.0
      solver_type: 1
    substeps: 1
    up_axis: 1
terrain:
  desc: null
  value:
    border_size: 25
    curriculum: false
    discrete_height_range:
    - 0.0
    - 0.01
    dynamic_friction: 0.6
    horizontal_scale: 0.1
    max_init_terrain_level: 5
    measure_heights: false
    measured_base_points_x:
    - -0.8
    - -0.7
    - -0.6
    - -0.5
    - -0.4
    - -0.3
    - -0.2
    - -0.1
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    measured_base_points_y:
    - -0.5
    - -0.4
    - -0.3
    - -0.2
    - -0.1
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    measured_feet_points_x:
    - -0.8
    - -0.7
    - -0.6
    - -0.5
    - -0.4
    - -0.3
    - -0.2
    - -0.1
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    measured_feet_points_y:
    - -0.5
    - -0.4
    - -0.3
    - -0.2
    - -0.1
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    measured_points_x:
    - -0.8
    - -0.7
    - -0.6
    - -0.5
    - -0.4
    - -0.3
    - -0.2
    - -0.1
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    measured_points_y:
    - -0.5
    - -0.4
    - -0.3
    - -0.2
    - -0.1
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    mesh_type: trimesh
    num_cols: 20
    num_height: 187
    num_rows: 20
    num_sub_terrains: 400
    platform: 3.0
    restitution: 0.0
    rough_flat_range:
    - 0.005
    - 0.01
    rough_slope_range:
    - 0.005
    - 0.02
    selected: false
    slope_range:
    - 0
    - 0.1
    slope_treshold: 0.75
    stair_height_range:
    - 0.01
    - 0.1
    stair_width_range:
    - 0.25
    - 0.25
    static_friction: 0.6
    terrain_dict:
      discrete: 0.1
      flat: 0.3
      rough flat: 0.2
      rough slope down: 0.0
      rough slope up: 0.0
      slope down: 0.2
      slope up: 0.2
      stairs down: 0.0
      stairs up: 0.0
      wave: 0.0
    terrain_kwargs: null
    terrain_length: 8.0
    terrain_proportions:
    - 0.3
    - 0.2
    - 0.2
    - 0.2
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.1
    - 0.0
    terrain_width: 8.0
    vertical_scale: 0.005
viewer:
  desc: null
  value:
    lookat:
    - 11.0
    - 5
    - 3.0
    pos:
    - 10
    - 0
    - 6
    ref_env: 0
